### ISSUE TITLE
Blitz-stats roadmap

### ISSUE THREAD

**Issue by Jylpah** [Jylpah/blitz-stats#61]
# Working on 

(slowly)

- [ ] REFACTOR code to [Pydantic v2](https://docs.pydantic.dev/2.0/blog/pydantic-v2-final/)
- [ ] Generalize [Arrow](https://arrow.apache.org/) data writer 
- [ ] Add data export of account stats over releases
